# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161028_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='number_series',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='series',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=set([('tv_series', 'number')]),
        ),
    ]
