# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161028_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='last_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
