# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161028_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userseries',
            old_name='serial',
            new_name='tv_series',
        ),
        migrations.AlterField(
            model_name='userseries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_series', to='core.TelegramUser'),
        ),
    ]
