# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:29
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='series',
            name='dc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
