# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161029_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='sites_cinema',
            field=models.ManyToManyField(related_name='bots', to='core.SiteCinema'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='sites_news',
            field=models.ManyToManyField(related_name='bots', to='core.SiteNews'),
        ),
        migrations.AlterUniqueTogether(
            name='usernews',
            unique_together=set([('user', 'site_news')]),
        ),
        migrations.AlterUniqueTogether(
            name='userseries',
            unique_together=set([('user', 'tv_series')]),
        ),
    ]
