# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161030_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='sites_cinema',
            field=models.ManyToManyField(blank=True, null=True, related_name='bots', to='core.SiteCinema'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='sites_news',
            field=models.ManyToManyField(blank=True, null=True, related_name='bots', to='core.SiteNews'),
        ),
    ]
