# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:00
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161030_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=255)),
                ('name_eng', models.CharField(blank=True, max_length=255)),
                ('date_release_last_ongoing_series', models.DateTimeField(default=datetime.datetime.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_series', to='core.SiteCinema')),
            ],
            options={
                'ordering': ('date_release_last_ongoing_series',),
            },
        ),
        migrations.RemoveField(
            model_name='sitetvseries',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='series',
            old_name='dc',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='usernews',
            old_name='dc',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='userseries',
            old_name='dc',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dc',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.TVSeries'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='sites_cinema',
            field=models.ManyToManyField(blank=True, related_name='bots', to='core.SiteCinema'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='sites_news',
            field=models.ManyToManyField(blank=True, related_name='bots', to='core.SiteNews'),
        ),
        migrations.AlterField(
            model_name='userseries',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.TVSeries'),
        ),
        migrations.DeleteModel(
            name='SiteTVSeries',
        ),
    ]
