# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:07
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161031_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ('-date_release_last_ongoing_series',)},
        ),
        migrations.AddField(
            model_name='sitecinema',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitenews',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(blank=True, help_text='Set from telegram.api get_me', max_length=255),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(blank=True, help_text='Set from telegram.api get_me', max_length=255),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='date_release_last_ongoing_series',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
