# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Site address')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RssNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.Rss')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tvseries',
            options={'ordering': ('date_release_last_ongoing_series',)},
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='rss',
            field=models.ManyToManyField(blank=True, related_name='bots', to='core.Rss'),
        ),
    ]
