# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161028_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(blank=True, help_text='Set in save', max_length=255),
        ),
    ]
