# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_telegrambot_last_message_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together=set([('user_id', 'bot')]),
        ),
    ]
