# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:58
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161028_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('name_rus', models.CharField(blank=True, max_length=255)),
                ('name_eng', models.CharField(blank=True, max_length=255)),
                ('number', models.FloatField(blank=True, null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Site address')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('site_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.SiteNews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites_news', to='core.TelegramUser')),
            ],
        ),
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteCinema',
        ),
        migrations.AddField(
            model_name='series',
            name='dc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.SiteNews'),
        ),
    ]
