# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161029_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
