# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170317_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssnews',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitecinema',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitenews',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssnews',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rssnews',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(blank=True, help_text='From telegram.api get_me', max_length=255),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(blank=True, help_text='From telegram.api get_me', max_length=255),
        ),
    ]
