# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170326_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
